use rdkafka::{ClientConfig,Message,Offset,TopicPartitionList,consumer::{BaseConsumer,Consumer},producer::{BaseProducer,BaseRecord,Producer}};
use std::{time::{Duration,Instant},io::{self,Read}};
fn main()->Result<(),Box<dyn std::error::Error>>{
 let a:Vec<String>=std::env::args().collect(); let c:serde_json::Value=serde_json::from_slice(&std::fs::read(&a[2])?)?;let cfg=&c["mode"]["config"];let brokers=cfg["brokers"].as_str().unwrap();let topic=cfg["state_topic"].as_str().unwrap();let n=c["expected_partitions"].as_array().unwrap().len();let d=Duration::from_secs(10);
 if a[1]=="write"{let p:BaseProducer=ClientConfig::new().set("bootstrap.servers",brokers).create()?;let mut input=String::new();io::stdin().read_to_string(&mut input)?;for l in input.lines(){let v:serde_json::Value=serde_json::from_str(l)?;let key:Vec<u8>=serde_json::from_value(v["key"].clone())?;let payload=v["payload"].as_str();let rec=BaseRecord::<Vec<u8>,str>::to(topic).partition(v["partition"].as_i64().unwrap() as i32).key(&key);p.send(if let Some(x)=payload{rec.payload(x)}else{rec}).map_err(|(e,_)|e)?;}p.flush(d)?;return Ok(())}
 let con:BaseConsumer=ClientConfig::new().set("bootstrap.servers",brokers).set("group.id",format!("review-raw-{}",std::process::id())).set("enable.auto.commit","false").set("enable.auto.offset.store","false").set("isolation.level","read_committed").set("enable.partition.eof","true").create()?;
 let mut tpl=TopicPartitionList::new();let mut ends=std::collections::BTreeMap::new();for p in 0..n{tpl.add_partition_offset(topic,p as i32,Offset::Beginning)?;ends.insert(p,con.fetch_watermarks(topic,p as i32,d)?);}con.assign(&tpl)?;let mut done=std::collections::BTreeSet::new();let now=Instant::now();let mut out=vec![];
 while done.len()<n{assert!(now.elapsed()<Duration::from_secs(60));match con.poll(Duration::from_millis(10)){Some(Ok(m))=>{out.push(serde_json::json!({"partition":m.partition(),"offset":m.offset(),"key":m.key(),"payload":m.payload().map(|p|String::from_utf8_lossy(p).to_string())}));},Some(Err(rdkafka::error::KafkaError::PartitionEOF(p)))=>{done.insert(p);},Some(Err(e))=>return Err(e.into()),None=>{}}}
 println!("{}",serde_json::json!({"records":out,"watermarks":ends}));Ok(())
}
