import React,{useEffect,useLayoutEffect} from 'react';import{createRoot}from'react-dom/client';
import{BrowserProductProvider,ProductProvider,createTopicHooks,defineJoin}from'./product-provider';import{aggregateDecimal,type BrowserCatalog}from'./topic-schema';
import{schemas}from'./generated/expanded-topics';
const observed:Record<string,unknown>={};let provider:BrowserProductProvider|undefined,root:ReturnType<typeof createRoot>|undefined;
function start(url:string,token:string,catalog:BrowserCatalog,fieldPatches=false){const typedCatalog={shit:{schema:schemas.shit,fingerprint:catalog.shit.fingerprint},nested_positions:{schema:schemas.nested_positions,fingerprint:catalog.nested_positions.fingerprint}};const hooks=createTopicHooks(typedCatalog);provider=new BrowserProductProvider({mode:'remote',url,token,catalog,subscriptions:32,...(fieldPatches?{fieldPatches:true}:{})});const spec={left:{topic:'shit',as:'l'},right:{topic:'nested_positions',as:'r'},kind:'left',cardinality:'many_to_one',on:{left:'oo.name',right:'details.name'},limits:{maxLeftRowsPerKey:4,maxOutputRows:1000}} as const;const joined=defineJoin(typedCatalog,spec),inner=defineJoin(typedCatalog,{...spec,kind:'inner'});
 const raw={select:['l.label','l.oo.name','l.oo.note','r.details.price'],orderBy:[{field:'l.label',direction:'asc'}]}as const;
 function App(){const a=hooks.useLiveQuery(joined,raw),b=hooks.useLiveQuery(inner,raw),g=hooks.useLiveQuery(joined,{global:true,aggregates:{n:{aggFunc:'count'},sum:{aggFunc:'sum',field:'r.details.price'}},orderBy:[]}as const);const grouped=hooks.useLiveQuery(joined,{groupBy:['l.label'],aggregates:{sum:{aggFunc:'sum',field:'r.details.price'}},having:{op:'gt',field:'sum',value:aggregateDecimal('0')},orderBy:[]} as const);const view=hooks.useLiveQueryViewport(joined),helper=view.useWholeResult(raw);
 useLayoutEffect(()=>{Object.assign(observed,{left:a,inner:b,global:g,grouped,helper});},[a,b,g,grouped,helper]);useEffect(()=>{const handle=view.viewport.replace({query:raw,window:{firstRow:0,lastRow:1},sink:{setRowCount(count){observed.count=count;},setRowData(rows){observed.window=rows;}}});return()=>handle.release();},[view.viewport]);return <output>{a.status}:{b.status}:{g.status}</output>;}
 root=createRoot(document.getElementById('root')!);root.render(<ProductProvider provider={provider}><App/></ProductProvider>);}
Object.assign(window,{joinDemo:{start,observe:()=>({...observed,diagnostics:provider?.connectionDiagnostics,errors:provider?.consumerErrors}),dispose:()=>{root?.unmount();provider?.dispose();}}});
