import React,{useEffect,useState,useLayoutEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserProductProvider,ProductProvider,createTopicHooks,useConnectionStatus,useViewServerHealthSummary} from './product-provider';
import {createBrowserTelemetry} from './browser-telemetry';
import type {BrowserCatalog,TopicQuery,Schema} from './topic-schema';
const observations:unknown[]=[];const latest:Record<string,unknown>={};const windows:Record<string,unknown>={};let provider:BrowserProductProvider|undefined;let switchTopic:(s:string)=>void=()=>{};let activeConnections=0;let telemetry:ReturnType<typeof createBrowserTelemetry>|undefined;let root:ReturnType<typeof createRoot>|undefined;const controls:Record<string,{query:(q:TopicQuery<Schema>)=>void;window:(first:number,last:number)=>void}>={};
const q=(topic:string):TopicQuery<Schema>=>topic==='products'?{select:['id','quantity'],orderBy:[{field:'amount',direction:'asc'}]}:topic==='orders'?{select:['customer','units','price','note'],orderBy:[{field:'price',direction:'asc'},{field:'customer',direction:'desc'}]}:topic==='positions'?{select:['symbol','quantity','risk','hedged'],orderBy:[{field:'risk',direction:'desc'},{field:'quantity',direction:'asc'}]}:{select:['recordId','field01','field35'],orderBy:[{field:'field01',direction:'desc'}]};
function start(url:string,token:string,catalog:BrowserCatalog,endpoint?:string,queries?:Record<string,TopicQuery<Schema>>){
 if(provider)throw Error('already started');const hooks=createTopicHooks(catalog);telemetry=endpoint?createBrowserTelemetry({endpoint:endpoint+'/v1/traces',sampleRatio:1,deployment:'local-qualification'}):undefined;provider=new BrowserProductProvider({mode:'remote',url,token,catalog,subscriptions:16},telemetry);activeConnections++;
 function EntityRow({topic,row}:{topic:string;row:Record<string,unknown>&{readonly rowId:string}}){const[state]=useState(()=>String(row.customer??row.symbol??row.recordId??row.rowId));return <li data-row-id={row.rowId} data-local-state={state}>{JSON.stringify(row)}</li>;}
 function Dataset({topic}:{topic:string}){const[query,setQuery]=useState(()=>queries?.[topic]??q(topic));const whole=hooks.useLiveQuery(topic,query),view=hooks.useLiveQueryViewport(topic);
 useEffect(()=>{const generation=view.viewport.replace({query,window:{firstRow:0,lastRow:1},sink:{setRowCount(count){windows[topic]={...(windows[topic] as object??{}),totalRows:count};},setRowData(rows,keys){windows[topic]={...(windows[topic] as object??{}),rows,keys};}}});controls[topic]={query:setQuery,window:(first,last)=>generation.setWindow({firstRow:first,lastRow:last})};return()=>{delete controls[topic];generation.release()};},[topic,view.viewport,query]);
 useLayoutEffect(()=>{const span=whole.observationTraceContext?telemetry?.start('dom_observation',whole.observationTraceContext):undefined;latest[topic]=whole;observations.push({at:performance.now(),topic,whole,viewport:windows[topic]});span?.end();},[topic,whole.rows,whole.version,whole.status]);
 return <section data-topic={topic}><h2>{topic}</h2><output>{whole.status}:{view.status}</output><pre>{JSON.stringify(whole.rows)}</pre><ul>{whole.rows.map(row=><EntityRow key={row.rowId} topic={topic} row={row}/>)}</ul></section>;}
 function Switch(){const[topic,setTopic]=useState(Object.keys(catalog)[0]);switchTopic=setTopic;const whole=hooks.useLiveQuery(topic,queries?.[topic]??q(topic));useEffect(()=>{latest.switch={topic,...whole};},[topic,whole.rows,whole.status]);return <section data-switch={topic}><output>{whole.status}</output><pre>{JSON.stringify(whole.rows)}</pre></section>}
 function App(){const connection=useConnectionStatus(),health=useViewServerHealthSummary();useEffect(()=>{latest.health=health;latest.connection=connection;},[health,connection]);return <><h1>One service, configured datasets</h1><div id="connection">{connection}</div><div id="health">{health.status}:{String(health.ready)}</div>{Object.keys(catalog).map(topic=><Dataset key={topic} topic={topic}/>)}<Switch/></>}
 root=createRoot(document.getElementById('root')!);root.render(<ProductProvider provider={provider}><App/></ProductProvider>);
}
Object.assign(window,{topicsDemo:{start,observe:()=>({latest,windows,observations,activeConnections,rowLocalState:Object.fromEntries([...document.querySelectorAll('section[data-topic]')].map(section=>[section.getAttribute('data-topic'),Object.fromEntries([...section.querySelectorAll('[data-row-id]')].map(row=>[row.getAttribute('data-row-id'),row.getAttribute('data-local-state')]))]))}),provider:()=>provider,changeWindow:(topic:string,offset:number,limit:number)=>controls[topic]?.window(offset,offset+limit-1),changeQuery:(topic:string,query:TopicQuery<Schema>)=>controls[topic]?.query(query),replace:(topic:string)=>switchTopic(topic),dispose:async()=>{root?.unmount();provider?.dispose();await telemetry?.shutdown();}}});
