import {createRequire} from 'node:module';import {readFile,writeFile} from 'node:fs/promises';import {spawn} from 'node:child_process';import {once} from 'node:events';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
const root=new URL('../',import.meta.url).pathname,req=createRequire(root+'browser/package.json'),{chromium}=req('playwright');const cp=process.argv[2],mode=process.argv[3],runtime=process.argv[4],cfg=JSON.parse(await readFile(cp,'utf8'));const browser=await chromium.launch({headless:true});let slow;const samples=[];
try{const page=await browser.newPage();await page.addInitScript(()=>{window.f1Notifications=[];const Native=window.Worker;window.Worker=class extends Native{constructor(...args){super(...args);this.addEventListener('message',e=>{if(e.data?.type==='live'){for(const result of Object.values(e.data.results))window.f1Notifications.push({at:performance.now(),sequence:result.remote?.sourceSequence});}})}}});
 await page.exposeFunction('f1Feed',async label=>{const t=performance.now();const p=spawn(runtime+'/kafka_probe',['feed',cp],{env:process.env,stdio:['pipe','pipe','pipe']});let err='';p.stderr.on('data',d=>err+=d);p.stdout.resume();p.stdin.end(JSON.stringify({id:'a',partition:0,quantity:'9223372036854775807',amount:'-10.01',label})+'\n');const[code]=await once(p,'exit');assert.equal(code,0,err);return {producerProcessMs:performance.now()-t};});
 await page.goto(cfg.origin+'/remote-demo.html');await page.evaluate(async({url,token})=>{const m=await import('/f1-latency.tsx');await m.mount(url,token);},{url:'ws://'+cfg.bind+'/v13',token:process.env.V12_SESSION_TOKEN});await page.waitForFunction(()=>window.f1?.samples.length>0);assert.equal(await page.evaluate(()=>window.f1.samples.at(-1).result.total_rows),32);
 if(mode==='pressure'){slow=spawn(runtime+'/f1_stalled_peer',[cp],{env:process.env,stdio:['pipe','pipe','pipe']});let out='',err='';slow.stderr.on('data',d=>err+=d);await new Promise((resolve,reject)=>{slow.stdout.on('data',d=>{out+=d;if(out.includes('PRESSURE_READY 99'))resolve();});slow.on('exit',code=>reject(Error('stalled helper exited '+code+' '+err)));});}
 const count=mode==='healthy'?20:8;
 for(let i=0;i<count;i++){const label='live-'+i;const sample=await page.evaluate(async({label})=>{const start=performance.now();const ack=await window.f1Feed(label);const ackAt=performance.now();const until=performance.now()+5000;while(!window.f1.samples.some(v=>v.label?.value===label)){if(performance.now()>until)throw Error('hook deadline');await new Promise(r=>setTimeout(r,1));}const s=window.f1.samples.find(v=>v.label?.value===label);const n=window.f1Notifications.find(v=>v.sequence===s.result.remote.sourceSequence);return {...s,triggerToReactCommitMs:s.at-start,producerAckReturnToReactCommitMs:s.at-ackAt,notificationToReactCommitMs:s.at-n.at,producerProcessMs:ack.producerProcessMs,remote:s.result.remote};},{label});
  assert.equal(sample.result.remote.sourceSequence,String(i+2));assert.equal(sample.result.total_rows,33);assert.equal(sample.result.rows[0].id,'a');assert.equal(sample.result.rows[0].quantity,'9223372036854775807');assert.deepEqual(sample.result.rows[0].amount,{coefficient:'-1001',scale:2});assert.equal(sample.dom,label);samples.push(sample);}
 await page.evaluate(()=>window.f1.close());console.log(JSON.stringify({mode,count,browser:await browser.version(),samples,boundaries:'Browser same-clock trigger before source producer invocation to React layout-effect DOM observation; includes feeder/producer overhead, not native application receipt and not paint. Notification-to-React uses main-thread clock. Worker metadata intervals remain Worker-local; receivedNs is after decode/adaptation.'}));
}finally{if(slow){slow.stdin.end();await once(slow,'exit').catch(()=>{});}await browser.close();}
