import {createRequire} from 'node:module';import {readFile,writeFile} from 'node:fs/promises';import {spawn} from 'node:child_process';import {once} from 'node:events';import {createInterface} from 'node:readline';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
const root=new URL('../',import.meta.url).pathname,req=createRequire(root+'browser/package.json'),{chromium}=req('playwright');const cp=process.argv[2],mode=process.argv[3],runtime=process.argv[4],cfg=JSON.parse(await readFile(cp,'utf8'));const browser=await chromium.launch({headless:true});let slow;const samples=[];const producer=spawn(runtime+'/hot_stream_producer',[cp],{env:process.env,stdio:['pipe','pipe','pipe']});const lines=createInterface({input:producer.stdout})[Symbol.asyncIterator]();let producerError='';producer.stderr.on('data',d=>producerError+=d);const first=await lines.next();assert.equal(JSON.parse(first.value).ready,true);
try{const page=await browser.newPage();await page.addInitScript(()=>{window.f1Notifications=[];const Native=window.Worker;window.Worker=class extends Native{constructor(...args){super(...args);this.addEventListener('message',e=>{if(e.data?.type==='live'){for(const result of Object.values(e.data.results))window.f1Notifications.push({at:performance.now(),sequence:result.remote?.sourceSequence});}})}}});
 await page.exposeFunction('f1Feed',async label=>{const t=performance.now();producer.stdin.write(JSON.stringify({id:'a',label})+'\n');const value=JSON.parse((await lines.next()).value);assert.equal(value.label,label);return {producerProcessMs:performance.now()-t,producer:value};});
 await page.goto(cfg.origin+'/remote-demo.html');await page.evaluate(async({url,token})=>{const m=await import('/f1-latency.tsx');await m.mount(url,token);},{url:'ws://'+cfg.bind+'/v14',token:process.env.V12_SESSION_TOKEN});await page.waitForFunction(()=>window.f1?.samples.length>0);assert.equal(await page.evaluate(()=>window.f1.samples.at(-1).result.total_rows),Number(process.env.HOT_SEEDS||32));
 const initialSequence=Number(await page.evaluate(()=>window.f1.samples.at(-1).result.remote.sourceSequence));
 const count=Number(process.env.HOT_COUNT||(mode==='healthy'?20:8));const warmups=Number(process.env.HOT_WARMUPS||3);
 for(let j=0;j<warmups;j++){await page.evaluate(async label=>{await window.f1Feed(label);while(!window.f1.samples.some(v=>v.label?.value===label))await new Promise(r=>setTimeout(r,1));},'warm-'+j);}
 if(mode==='pressure'){slow=spawn(runtime+'/f1_stalled_peer',[cp],{env:process.env,stdio:['pipe','pipe','pipe']});let out='',err='';slow.stderr.on('data',d=>err+=d);await new Promise((resolve,reject)=>{slow.stdout.on('data',d=>{out+=d;if(out.includes('PRESSURE_READY 99'))resolve();});slow.on('exit',code=>reject(Error('stalled helper exited '+code+' '+err)));});}

 for(let i=0;i<count;i++){const label='live-'+i;const sample=await page.evaluate(async({label})=>{const start=performance.now();const ack=await window.f1Feed(label);const ackAt=performance.now();const until=performance.now()+5000;while(!window.f1.samples.some(v=>v.label?.value===label)){if(performance.now()>until)throw Error('hook deadline');await new Promise(r=>setTimeout(r,1));}const s=window.f1.samples.find(v=>v.label?.value===label);const n=window.f1Notifications.find(v=>v.sequence===s.result.remote.sourceSequence);return {...s,triggerToReactCommitMs:s.at-start,producerAckReturnToReactCommitMs:s.at-ackAt,notificationToReactCommitMs:s.at-n.at,producerProcessMs:ack.producerProcessMs,producer:ack.producer,remote:s.result.remote};},{label});
  assert.equal(sample.result.remote.sourceSequence,String(initialSequence+i+1+warmups));assert.equal(sample.result.total_rows,Number(process.env.HOT_SEEDS||32)+1);assert.equal(sample.result.rows[0].id,'a');assert.equal(sample.result.rows[0].quantity,'9223372036854775807');assert.deepEqual(sample.result.rows[0].amount,{coefficient:'-1001',scale:2});assert.equal(sample.dom,label);samples.push(sample);}
 await page.evaluate(()=>window.f1.close());console.log(JSON.stringify({mode,count,warmups,seeds:Number(process.env.HOT_SEEDS||32),browser:await browser.version(),samples,boundaries:'Browser same-clock trigger before long-lived source producer IPC request to React layout-effect DOM observation; includes IPC/source broker delivery and consumer wait; no per-update process startup, not native application receipt and not paint. Notification-to-React uses main-thread clock. Worker metadata intervals remain Worker-local; receivedNs is after decode/adaptation.'}));
}finally{producer.stdin.end();await once(producer,'exit').catch(()=>{});if(slow){slow.stdin.end();await once(slow,'exit').catch(()=>{});}await browser.close();}
