"""Recompute summary and human tables from the exact, verified raw sample matrix."""
from pathlib import Path
import json,runpy,re
root=Path(__file__).resolve().parent.parent;out=root/'evidence/v11/measurements'
summary=runpy.run_path(str(root/'scripts/verify-v11-measurements.py'))['verify']()
(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
lines=['# V11 bounded local measurements','',f"{summary['runs']} completed release processes; {summary['oracle_samples']} exact-oracle measured completions, plus eight oracle-checked warmup batches per process. Five preliminary v10 processes precede production edits; the final comparison has two processes / 64 samples per cell. The explicitly interrupted development attempt is excluded.",'','Fixed 10,000 initial live rows; P/L and actual row distribution are in every setup record; H=256, two predicate shapes and four subscriptions. K is per-sample distinct touched keys. Same Rust 1.96.1 release/common harness/SQLite settings/source and query data. Seed 90210. Measurements ran serially with no concurrent tests/builds. Host/OS background activity was not controlled.','', '## Completed service and formation','', 'All times are milliseconds per batch. The service interval includes durable completion, reconciliation and four complete reads; it excludes fixture construction, formation waiting and the separate local authorization callback. Rates are records AND batches per measured service second, not transaction-only or end-to-end production capacity.','', '| Candidate | P | L | Cap | Traffic | Durable p50 | COMMIT p50 | Reconcile p50 | Four reads p50 | Formation p50 | Service p50/p95/p99/max | Records/s | Batches/s |','|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---|---:|---:|']
for x in summary['cells']:
 q=x['service_ms'];lines.append(f"| {x['candidate']} | {x['P']} | {x['L']} | {x['cap']} | {x['mode']} | {x['durable_ms']['p50']:.3f} | {x['commit_ms']['p50']:.3f} | {x['reconciliation_ms']['p50']:.3f} | {x['read_ms']['p50']:.3f} | {x['batch_build_ms']['p50']:.3f} | "+'/'.join(f'{q[k]:.3f}' for k in ['p50','p95','p99','max'])+f" | {x['records_per_service_second']:.1f} | {x['batches_per_service_second']:.1f} |")
lines+=['','## Source-record latency and sparse traffic','','The latency starts at each record’s fixture construction and ends when all query results complete. It includes actual batch formation/deadline wait, with the oracle outside timing. Dense deadline is 1,000 ms (size flush); sparse deadline is 4 ms (one record per arrival). Cap=1 seals immediately. These are local decoded-input observations, excluding broker/network/Registry. Within-batch record observations are correlated.','','| Candidate | P | L | Cap | Traffic | Record wait p50/p95/p99/max | Record-to-result p50/p95/p99/max | Authorization p50 |','|---|---:|---:|---:|---|---|---|---:|']
for x in summary['cells']:
 vals=lambda name:'/'.join(f"{x[name][k]:.3f}" for k in ['p50','p95','p99','max'])
 lines.append(f"| {x['candidate']} | {x['P']} | {x['L']} | {x['cap']} | {x['mode']} | {vals('record_wait_ms')} | {vals('record_latency_ms')} | {x['authorize_ms']['p50']:.3f} |")
lines+=['','## Direct work counts','','Unchanged full-history guards: one global object plus L partition objects per read; four reads perform four global reads and 4L partition reads, decode 1,024 global batch identities and 1,024L partition record identities, and issue 4(L+3) SQL dispatches. These are application operations, not physical pages or fsyncs. A mutation plus reconciliation guard reads two global and two target-partition objects, independent of stored P and query-owned L. Store receipts explicitly copy 3P coordinates; additional engine copying/comparison remains included in elapsed reconciliation. Zero ordinary full scans/reconstructions.','','| Candidate | P | L | Cap | Query metadata bytes p50 | Guard validation p50 ms | Extraction p50 ms | Queue record visits per batch |','|---|---:|---:|---:|---:|---:|---:|---:|']
for x in summary['cells']:
 if x['mode']!='dense':continue
 lines.append(f"| {x['candidate']} | {x['P']} | {x['L']} | {x['cap']} | {x['query_metadata_bytes']['p50']:,.0f} | {x['guard_validation_ms']['p50']:.3f} | {x['guard_action_ms']['p50']:.3f} | {x['queue_records_serialized']['p50']:,.0f} |")
lines+=['','## Process resources and limits','','CPU/RSS include setup, acquisition audits, recovery and oracles; no per-stage CPU attribution. File sizes are final SQLite DB/WAL bytes, not physical write amplification. Detailed values are retained per process.','','| Candidate | P | L | Cap | Traffic | RSS MiB range | Process user+system CPU seconds range |','|---|---:|---:|---:|---|---|---|']
for x in summary['cells']:
 rss=[];cpu=[]
 for repeat in range(2):
  phase='large' if x['cap']==256 else 'small';name=f"{phase}-{x['candidate']}-p{x['P']}-l{x['L']}-cap{x['cap']}-{x['mode']}-r{repeat}"
  text=(out/(name+'.resources.txt')).read_text();rss.append(int(re.search(r'(\d+)\s+maximum resident set size',text).group(1))/1024**2)
  match=re.search(r'([\d.]+)\s+user\s+([\d.]+)\s+sys',text);cpu.append(float(match[1])+float(match[2]))
 lines.append(f"| {x['candidate']} | {x['P']} | {x['L']} | {x['cap']} | {x['mode']} | {min(rss):.2f}–{max(rss):.2f} | {min(cpu):.2f}–{max(cpu):.2f} |")
lines+=['','Nearest-rank p50/p95/p99/max for every recorded phase are in `evidence/v11/measurements/summary.json`. With 64 batch samples per cell, p99=max. These are bounded observations, not stable production tail estimates. No compact-read improvement is claimed: format-3 integrity remains unchanged and the O(L*H) guard cost is retained. Batching amortizes actual FULL-durability COMMIT over records; sparse traffic obtains no full-batch amortization and waits for the configured deadline.','', 'Cap=256 was admitted only after the recorded small-run resource check. Cap=1024 is covered by deterministic semantics/work tests but not timed. The local harness has zero spill/paused work, explicitly recorded; production bounds and actual SQLite-lock stalls have separate deterministic/SDK evidence. Full final Recovery hashes match between candidates/repetitions for every cell. See V11-OWNED-READS-AND-BATCHING.md for integrity scope and the source-to-result timing boundary.','']
(root/'reports/V11-MEASUREMENTS.md').write_text('\n'.join(lines))
print(f"Reported {summary['oracle_samples']} exact samples")
