import {createRequire} from 'node:module';import {resolve} from 'node:path';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'..'),require=createRequire(root+'/browser/package.json'),{chromium}=require('playwright');const cfg=JSON.parse(await readFile(process.argv[2],'utf8'));const browser=await chromium.launch({headless:true});const cases=[];let page;let quotaTiming;const diagnostics=[];
try{page=await browser.newPage();page.setDefaultTimeout(30000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(cfg.origin+'/remote-demo.html');await page.waitForFunction(()=>!!window.v12);
await page.evaluate(async({cfg,token})=>window.v12.connect('review','ws://'+cfg.bind+'/v14',token,70),{cfg,token:process.env.V12_SESSION_TOKEN});
const q={where_expr:{op:'true'},direction:'ascending',offset:0,limit:16};
const first=await page.evaluate(q=>window.v12.snapshot('review','exact',q),q);assert.deepEqual(first.rows.map(r=>r.id),['a','b']);assert.equal(first.rows[0].quantity,'9223372036854775807');assert.deepEqual(first.rows[0].amount,{coefficient:'-123000000000000000009',scale:18});assert.deepEqual(first.rows[0].label,{state:'value',value:'nul\0 日本語🦀'});cases.push('independent-exact-integer-decimal-Unicode-label');
await page.evaluate(()=>window.v12.apply('review',{command:'close',subscription:'exact'}));
await page.evaluate(()=>window.v12.mount('review'));await page.waitForFunction(()=>document.querySelector('[data-testid="review"]')?.textContent==='2|a,b');cases.push('mounted-useLiveQuery');
await page.evaluate(()=>window.v12.mountViewport('review'));await page.waitForFunction(()=>document.querySelector('[data-testid="viewport"]')?.textContent==='ready');const windowRows=await page.evaluate(()=>JSON.parse(document.getElementById('root').dataset.window));assert.equal(Object.values(windowRows)[0].id,'b');cases.push('mounted-useLiveQueryViewport');
await page.evaluate(()=>window.v12.unmount());await page.waitForFunction(()=>window.v12.admission('review').subscriptions===0);
await page.evaluate(({cfg,token})=>{window.v12.close('review');window.v12.begin('review','ws://'+cfg.bind+'/v14',token,70);window.v12.mountBurst('review',71)},{cfg,token:process.env.V12_SESSION_TOKEN});const quotaStart=performance.now();let original30sPassed=true;try{await page.waitForFunction(()=>Object.values(window.v12.mounted).length===71&&Object.values(window.v12.mounted).every(v=>v.status!=='loading'),null,{timeout:30000});}catch(e){original30sPassed=false;await page.waitForFunction(()=>Object.values(window.v12.mounted).length===71&&Object.values(window.v12.mounted).every(v=>v.status!=='loading'),null,{timeout:60000});}quotaTiming={original30sPassed,settledMs:performance.now()-quotaStart,diagnosticMaximumMs:90000};const mounted=await page.evaluate(()=>Object.values(window.v12.mounted));assert.equal(mounted.filter(v=>v.status==='ready').length,70);assert.equal(mounted.filter(v=>v.status==='error').length,1);cases.push('70-plus-1-quota-shared-shapes-different-windows');
await page.evaluate(()=>window.v12.unmount());await page.waitForFunction(()=>window.v12.admission('review').subscriptions===0&&window.v12.admission('review').outstanding===0);cases.push('reserved-cleanup-zero-provider-subscriptions');
await page.evaluate(q=>window.v12.snapshot('review','survivor',q),q);const rejection=await page.evaluate(async()=>{try{await window.v12.apply('review',{command:'change_query',subscription:'survivor',query:{where_expr:{op:'condition',args:{field:'amount',condition:{op:'equal',value:{coefficient:'1',scale:10001}}}},direction:'ascending',offset:0,limit:4}});return false}catch{return true}});assert(rejection);
const survivor=await page.evaluate(()=>window.v12.apply('review',{command:'change_window',subscription:'survivor',offset:0,limit:16}));assert.equal(survivor.survivor.total_rows,2);cases.push('invalid-replacement-survivor');await page.evaluate(()=>window.v12.apply('review',{command:'close',subscription:'survivor'}));
const four=await page.evaluate(q=>Promise.all([0,1,2,3].map(n=>window.v12.snapshot('review','flight'+n,{...q,offset:n%2,limit:1}))),q);assert(four.every(r=>r.total_rows===2));cases.push('four-concurrent-commands');await page.evaluate(async()=>{for(let n=0;n<4;n++)await window.v12.apply('review',{command:'close',subscription:'flight'+n})});
for(const action of ['replace','release','invalidate-throw']){await page.evaluate(action=>window.v12.mountCallback('review',action),action);await page.waitForFunction(()=>window.v12.callbackLog.includes('old-count'));if(action==='replace')await page.waitForFunction(()=>window.v12.callbackLog.includes('new-data'));else await page.waitForFunction(()=>window.v12.admission('review').outstanding===0);const log=await page.evaluate(()=>window.v12.callbackLog);assert(!log.includes('old-data'));if(action==='replace')assert(log.includes('new-data'));await page.evaluate(()=>window.v12.unmount());cases.push('reentrant-'+action)}
await page.evaluate(()=>window.v12.close('review'));await page.evaluate(async({cfg,token})=>window.v12.connect('reconnect','ws://'+cfg.bind+'/v14',token,70),{cfg,token:process.env.V12_SESSION_TOKEN});const reconnect=await page.evaluate(q=>window.v12.snapshot('reconnect','again',q),q);assert.deepEqual(reconnect.rows,first.rows);await page.evaluate(()=>window.v12.close('reconnect'));cases.push('reconnect-state-convergence');assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,cases,quotaTiming,first,windowRows,browser:await browser.version()}));
}catch(error){console.error(JSON.stringify({error:String(error),cases,diagnostic:await page.evaluate(()=>({mounted:window.v12.mounted,admission:window.v12.admission('review'),html:document.getElementById('root').innerText})).catch(e=>String(e))}));throw error}finally{await browser.close()}
