import fs from 'node:fs';import assert from 'node:assert/strict';
import {reconstruct} from '../browser/src/row-delta.mjs';import {validateQuery,validateGroupedRow,queryFields,groupId,resultShape} from '../browser/src/topic-schema.ts';
import type {GroupedQuery,Schema} from '../browser/src/topic-schema.ts';
const [directory]=process.argv.slice(2),config=JSON.parse(fs.readFileSync(directory+'/configuration.json','utf8')),wire=JSON.parse(fs.readFileSync(directory+'/wire.json','utf8'));
const catalog=Object.fromEntries(config.catalog.topics.map((t:{topic:string;schema:string})=>[t.topic,{fingerprint:t.schema,schema:config.catalog.schemas.find((s:Schema)=>s.id===t.topic+'_v2')}])) as Record<string,{fingerprint:string;schema:Schema}>;
const bases=new Map();let frames=0,negatives=0,snapshots=0,deltas=0;
for(const f of wire){const v=f.value,b=v.result;if(v.type!=='result'||b.result_kind!=='grouped_v1')continue;const entry=catalog[b.topic],descriptor=JSON.parse(b.result_shape);const query={groupBy:descriptor[3],aggregates:Object.fromEntries(descriptor[4].map(([alias,aggFunc,field]:[string,string,string|null])=>[alias,{aggFunc,...(field===null?{}:{field})}])),orderBy:[]};validateQuery(entry.schema,query);const q=query as GroupedQuery<Schema>;assert.equal(b.result_shape,resultShape(b.topic,entry.fingerprint,q));
 const contract={topic:b.topic,schema:entry.fingerprint,fields:queryFields(q),key:'rowId',validate:(r:unknown,s:readonly string[])=>validateGroupedRow(entry.schema,q,r,s),validateKeys:(keys:string[],rows:Record<string,unknown>[])=>{for(let i=0;i<keys.length;i++)assert.equal(keys[i],groupId(b.topic,entry.fingerprint,entry.schema,q,rows[i]));}};
 const id=JSON.stringify([v.incarnation,v.connection,v.subscription,v.acquisition]),prior=bases.get(id);const next=reconstruct(prior,b,contract);bases.set(id,next);frames++;b.kind==='snapshot'?snapshots++:deltas++;
 if(b.kind==='snapshot'&&b.rows.length&&negatives===0){for(const mutate of [(x:typeof b)=>{x.rows[0].rowId=x.keys[0];},(x:typeof b)=>{delete x.rows[0][Object.keys(q.aggregates)[0]];},(x:typeof b)=>{x.keys[0]='rid2:0101010000000161';},(x:typeof b)=>{x.rows[0][Object.keys(q.aggregates)[0]]=NaN;},(x:typeof b)=>{x.projection.push('unselected');}]){const poisoned=structuredClone(b);mutate(poisoned);assert.throws(()=>reconstruct(undefined,poisoned,contract));negatives++;}}
 if(b.kind==='delta'){const wrong=structuredClone(b);wrong.result_shape+=' ';assert.throws(()=>reconstruct(prior,wrong,contract));const stale=structuredClone(b);stale.fromRevision++;assert.throws(()=>reconstruct(prior,stale,contract));}
}
assert(frames>0&&deltas>0&&negatives===5);const result={status:'PASS',scope:'replay of captured real MessagePack grouped results through production reconstruction plus malformed-row/ID/shape/revision rejection',frames,snapshots,deltas,negative_snapshot_vectors:negatives};fs.writeFileSync(directory+'/wire-validation.json',JSON.stringify(result,null,2));console.log(result);
